# Generated by Django 2.0 on 2017-12-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('textmsg', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
