# Generated by Django 2.0 on 2017-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20171221_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
