# Generated by Django 2.0 on 2017-12-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20171221_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
