# Generated by Django 2.0 on 2017-12-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20171221_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='date',
        ),
    ]
